name: run-tests
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run make test
        run: make test
      